name: Continuous integration
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  ci:
    runs-on: self-hosted
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        command: 
          - tidy
          - fmt
          - vet
          - test
          - coverage
          - build
    steps:
      - uses: actions/checkout@v3
      - run: make ${{ matrix.command }} 
